import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import fetch from "isomorphic-unfetch";
import ProductsDetails from "@/src/components/Home/ProductsDetails";
import Head from "next/head";
import Header from "@/src/components/Common/Header";
import Footer from "@/src/components/Common/Footer";
import Loading from "@/src/components/Home/Loading";

const ProductDetails = () => {
  const [product, setProduct] = useState(null);
  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    const fetchData = async () => {
      const res = await fetch(`/api/products/${id}`);
      const data = await res.json();
      setProduct(data);
    };

    if (id) {
      fetchData();
    }
  }, [id]);

  if (!product) {
    return <Loading />;
  }

  return (
    <>
      <Head>
        <title>Ecommarce</title>
        <meta name="description" content="Generated by farhad" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <ProductsDetails product={product} />
        <Footer />
      </main>
    </>
  );
};

export default ProductDetails;
