import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/src/components/Common/Header";
import Footer from "@/src/components/Common/Footer";
import ProductsDetails from "@/src/components/Home/ProductsDetails";

const inter = Inter({ subsets: ["latin"] });

export default function NotFoundPage() {
  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by farhad" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <ProductsDetails />
        <Footer />
      </main>
    </>
  );
}
