import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/src/components/Common/Header";
import Footer from "@/src/components/Common/Footer";
import SliderCarousel from "@/src/components/Home/Hero";
import Products from "@/src/components/Home/Products";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommarce</title>
        <meta name="description" content="Generated by farhad" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <SliderCarousel />
        <Products />
        <Footer />
      </main>
    </>
  );
}
